### PR TITLE
added made with open data survey and changed about section

### PR DESCRIPTION
**Pull request by j9recurses**
Added the made with open data survey and added profile to the about section in the website.

### CODE REVIEW

**Comment by jasonlally** [comment]
@j9recurses - I just modified the layout a little to fall in line with the other pages. Could you add some subtle style differences in the form, particularly to offset the question from the options. Could be as simple as making the font sizes a little different. Also, the link button to add an image isn't obvious at first.

snip

**Comment by j9recurses** [comment]
Yeah, no problem. I will try to fix the css on this.

**Comment by jasonlally** [comment]
Nvm on the button, there was a config for the button class in the form embed and I just added it.

**Comment by j9recurses** [comment]
Okay, css on the checkboxes and radio groups is fixed. To fix, one can just override the css classes that screendoor sets up.

**Comment by jasonlally** [comment]
Thanks, looks good :+1:

**Pull request merged**
